apiVersion: v2
appVersion: v0.0.3-alpha
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.14.1
- condition: localstack.enabled
  name: localstack
  repository: https://localstack.github.io/helm-charts
  version: 0.6.5
description: A Helm chart for automq-for-rocketmq
home: https://www.automq.com/
icon: https://www.automq.com/img/logo/logo-text.svg
maintainers:
- name: AutoMQ
name: automq-for-rocketmq
type: application
version: 0.0.6
